# Generated by Django 6.0 on 2025-12-10 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_portal', '0003_alter_appointment_test_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnalyte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=100)),
                ('analyte_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('normal_range_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal_range_high', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='QCLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=50, unique=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('received', 'Sample Received'), ('in_analysis', 'In Analysis'), ('awaiting_validation', 'Awaiting Validation'), ('report_ready', 'Report Ready')], default='received', max_length=30)),
                ('accessioned_date', models.DateTimeField(auto_now_add=True)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('processing_completed', models.DateTimeField(blank=True, null=True)),
                ('test_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='patient_portal.testorder')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entries', to='hematology.sample')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_type', models.CharField(blank=True, max_length=20)),
                ('validated', models.BooleanField(default=False)),
                ('validated_date', models.DateTimeField(blank=True, null=True)),
                ('analyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hematology.testanalyte')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hematology.sample')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
