# Generated by Django 6.0 on 2025-12-26 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient_portal', '0003_alter_appointment_test_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathologyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=100, unique=True)),
                ('dicom_file', models.FileField(blank=True, null=True, upload_to='dicom_slides/')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='dicom_previews/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sample_received', 'Sample Received'), ('awaiting_review', 'Awaiting Pathologist Review'), ('in_review', 'In Review'), ('report_ready', 'Report Ready')], default='sample_received', max_length=30)),
                ('body_part_examined', models.CharField(blank=True, max_length=100)),
                ('annotations', models.JSONField(blank=True, default=list)),
                ('pathologist_notes', models.TextField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_date', models.DateTimeField(blank=True, null=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='pathology_reports/')),
                ('study_date', models.DateField(blank=True, null=True)),
                ('icd_code', models.CharField(blank=True, max_length=20, null=True)),
                ('icd_description', models.CharField(blank=True, max_length=255, null=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathology_cases', to=settings.AUTH_USER_MODEL)),
                ('test_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathology_case', to='patient_portal.testorder')),
            ],
        ),
    ]
