# Generated by Django 5.2.9 on 2025-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathologycase',
            name='coronal_preview',
            field=models.ImageField(blank=True, null=True, upload_to='dicom_previews/'),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='is_volume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='modality',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='num_slices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='pixel_spacing_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='pixel_spacing_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='sagittal_preview',
            field=models.ImageField(blank=True, null=True, upload_to='dicom_previews/'),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='series_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='slice_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='volume_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='volume_file',
            field=models.FileField(blank=True, null=True, upload_to='dicom_volumes/'),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='volume_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='volume_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='window_center',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pathologycase',
            name='window_width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pathologycase',
            name='status',
            field=models.CharField(choices=[('sample_received', 'Sample Received'), ('awaiting_review', 'Awaiting Pathologist Review'), ('in_review', 'In Review'), ('report_ready', 'Report Ready'), ('processing', 'Processing Volume')], default='sample_received', max_length=30),
        ),
    ]
