# Generated by Django 6.0 on 2025-12-08 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='test_order',
        ),
        migrations.AddField(
            model_name='appointment',
            name='selected_tests',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='appointment',
            name='test_type',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('pathology', 'Pathology')], default='hematology', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='patient_portal.appointment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='testorder',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_orders', to='patient_portal.appointment'),
        ),
        migrations.AddField(
            model_name='testorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
