# Generated by Django 6.0 on 2025-12-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0002_remove_appointment_reason_remove_invoice_test_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='test_type',
            field=models.CharField(choices=[('hematology', 'Hematology'), ('pathology', 'Pathology')], default='hematology', max_length=20),
        ),
    ]
